---
- hosts: 10.0.3.14

  tasks:

  - name: Install apache2
    apt: name=apache2 update_cache=yes

  - name: Change apache2 default port 80 to 8888 and bind on loopback
    shell: cd /etc/apache2/ && sed 's/80/127\.0\.0\.1\:8888/g' ports.conf > ports.tmp && mv ports.tmp ports.conf

  - name: Install mod-php
    apt: name=libapache2-mod-php5 update_cache=yes

  - name: Restart apache2.
    service: name=apache2 state=restarted

  - name: Install nginx package
    apt: name=nginx update_cache=yes

